// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAcafJGFIUsIoaXEtEqp5ndFmBNtFO3VXE',
    appId: '1:100215584028:android:d4f41bbc438553c294f6d9',
    messagingSenderId: '100215584028',
    projectId: 'smart-supply-chains-8c321',
    storageBucket: 'smart-supply-chains-8c321.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCeLi48eDM5zILg1zWXeDR103JwBOZICEA',
    appId: '1:100215584028:ios:25fa302fecbd41e494f6d9',
    messagingSenderId: '100215584028',
    projectId: 'smart-supply-chains-8c321',
    storageBucket: 'smart-supply-chains-8c321.firebasestorage.app',
    iosClientId: '100215584028-geuc0v5khc3sj1dqpie0ca4qhmqp9rd9.apps.googleusercontent.com',
    iosBundleId: 'com.example.smartSupplyChain',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCeLi48eDM5zILg1zWXeDR103JwBOZICEA',
    appId: '1:100215584028:ios:25fa302fecbd41e494f6d9',
    messagingSenderId: '100215584028',
    projectId: 'smart-supply-chains-8c321',
    storageBucket: 'smart-supply-chains-8c321.firebasestorage.app',
    iosClientId: '100215584028-geuc0v5khc3sj1dqpie0ca4qhmqp9rd9.apps.googleusercontent.com',
    iosBundleId: 'com.example.smartSupplyChain',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC8SoNtv0Hgb86Cko63zDG2TMbFKFNrEJY',
    appId: '1:100215584028:web:a08fa016d733195294f6d9',
    messagingSenderId: '100215584028',
    projectId: 'smart-supply-chains-8c321',
    authDomain: 'smart-supply-chains-8c321.firebaseapp.com',
    storageBucket: 'smart-supply-chains-8c321.firebasestorage.app',
    measurementId: 'G-HR7PWY72HG',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC8SoNtv0Hgb86Cko63zDG2TMbFKFNrEJY',
    appId: '1:100215584028:web:a08fa016d733195294f6d9',
    messagingSenderId: '100215584028',
    projectId: 'smart-supply-chains-8c321',
    authDomain: 'smart-supply-chains-8c321.firebaseapp.com',
    storageBucket: 'smart-supply-chains-8c321.firebasestorage.app',
    measurementId: 'G-HR7PWY72HG',
  );

}